---
title: "Codebook"
author: "Tobi"
date: "12/13/2021"
output: pdf_document
---


## The run_analysis.R script performs the data preparation and then followed by the 5 steps required as described in the course project’s definition.

## Download the dataset
### Dataset downloaded and extracted under the folder called UCI HAR Dataset

## Assign each data to variables
### features <- features.txt 
### activities <- activity_labels.txt 
### subject_test <- test/subject_test.txt 
### x_test <- test/X_test.txt 
### y_test <- test/y_test.txt 
### subject_train <- test/subject_train.txt
### x_train <- test/X_train.txt 
### y_train <- test/y_train.txt

## Merges the training and the test sets to create one data set
### X is created by merging x_train and x_test using rbind() function
### Y is created by merging y_train and y_test using rbind() function
### Subject is created by merging subject_train and subject_test using rbind() function
### Merged_Data is created by merging Subject, Y and X using cbind() function

## Extract only the measurements on the mean and standard deviation for each measurement
### TidyData is created by subsetting Merged_Data, selecting only columns: subject, code and the measurements on the mean and standard deviation (std) for each measurement

## Uses descriptive activity names to name the activities in the data set
### Entire numbers in code column of the TidyData replaced with corresponding activity taken from second column of the activity’s variable

## Appropriately labels the data set with descriptive variable names
### code column in TidyData renamed into activities
### All Acc in column’s name replaced by Accelerometer
### All Gyro in column’s name replaced by Gyroscope
### All BodyBody in column’s name replaced by Body
### All Mag in column’s name replaced by Magnitude
### All start with character f in column’s name replaced by Frequency
### All start with character t in column’s name replaced by Time

## From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject
### FinalData is created by summarizing TidyData taking the means of each variable for each activity and each subject, after grouped by subject and activity.


```{r, echo=FALSE}
library(dplyr)

# Checking if archive already exists
filename<- "Coursera_GCD_Project.zip"
if(!file.exists("./data")){dir.create("./data")}
fileUrl<-"https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(fileUrl, filename)

# Checking if folder exists
if (!file.exists("UCI HAR Dataset")) { 
        unzip(fileused) 
}

features <- read.table("UCI HAR Dataset/features.txt", col.names = c("n","functions"))
activities <- read.table("UCI HAR Dataset/activity_labels.txt", col.names = c("code", "activity"))
subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt", col.names = "subject")
subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt", col.names = "subject")
x_test <- read.table("UCI HAR Dataset/test/X_test.txt", col.names = features$functions)
x_train <- read.table("UCI HAR Dataset/train/X_train.txt", col.names = features$functions)
y_test <- read.table("UCI HAR Dataset/test/y_test.txt", col.names = "code")
y_train <- read.table("UCI HAR Dataset/train/y_train.txt", col.names = "code")
xtable <- rbind(x_train, x_test)
ytable <- rbind(y_train, y_test)
Subject <- rbind(subject_train, subject_test)
Mergedfiles <- cbind(Subject, ytable, xtable)

combineddata <- Mergedfiles %>% select(subject, code, contains("mean"), contains("std"))

combineddata$code <- activities[combineddata$code, 2]

names(combineddata)[2] = "activity"
names(combineddata)<-gsub("Acc", "Accelerometer", names(combineddata))
names(combineddata)<-gsub("angle", "Angle", names(combineddata))
names(combineddata)<-gsub("BodyBody", "Body", names(combineddata))
names(combineddata)<-gsub("^f", "Frequency", names(combineddata))
names(combineddata)<-gsub("-freq()", "Frequency", names(combineddata), ignore.case = TRUE)
names(combineddata)<-gsub("gravity", "Gravity", names(combineddata))
names(combineddata)<-gsub("Gyro", "Gyroscope", names(combineddata))
names(combineddata)<-gsub("Mag", "Magnitude", names(combineddata))
names(combineddata)<-gsub("-mean()", "Mean", names(combineddata), ignore.case = TRUE)
names(combineddata)<-gsub("-std()", "STD", names(combineddata), ignore.case = TRUE)
names(combineddata)<-gsub("^t", "Time", names(combineddata))
names(combineddata)<-gsub("tBody", "TimeBody", names(combineddata))



FinalData <- combineddata %>%
        group_by(subject, activity) %>%
        summarise_all(funs(mean))
write.table(FinalData, "FinalData.txt", row.name=FALSE)

str(FinalData)

FinalData

```

